### ISSUE TITLE
Send to translation service bug

### ISSUE THREAD

**Issue by GiuseppeCSI** [micado-eu/pa_application#116]
When clicking on the send to translation button the process fails. The logs from portainer are the following

Importing translations for component "comments".
Importing translations for component "document_type".
Importing translations for component "event_category".
Importing translations for component "event_tag".
Importing translations for component "event".
Importing translations for component "glossary".
Importing translations for component "information_category".
Importing translations for component "intervention_category".
Importing translations for component "intervention_types".
Importing translations for component "process".
Unhandled error in GET /sendtotranslation: 500 error: value too long for type character varying(50)
    at Connection.parseE (/home/node/app/node_modules/pg/lib/connection.js:581:48)
    at Connection.parseMessage (/home/node/app/node_modules/pg/lib/connection.js:380:19)
    at Socket.<anonymous> (/home/node/app/node_modules/pg/lib/connection.js:116:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by gioppoluca** [comment]
should be closed by raising the lenght in the DB BUT keeping the old limit in the app so tranlstions have 20 characters buffer
