### ISSUE TITLE
Guided processes: If there is an error in batch uploading, page doesn't load

### ISSUE THREAD

**Issue by ivchicano** [micado-eu/pa_application#151]
When uploading batch processes, we encountered that rows in the process table were created without their respective rows created in process_translations table.

This makes it so the page doesn't load, with error `process is undefined`
Seems like the error is in the computed property filteredProcesses in this line:
https://github.com/micado-eu/pa_application/blob/af8fd1f2d65b5c9ce873f79e75c8b8de7d4ecda7/app/src/pages/ProcessManager.vue#L150

**Comment by ivchicano** [comment]
The backend emits this log:
```
backend_1             | (node:1) UnhandledPromiseRejectionWarning: error: value too long for type character varying(70)
backend_1             |     at Connection.parseE (/home/node/app/node_modules/pg/lib/connection.js:581:48)
backend_1             |     at Connection.parseMessage (/home/node/app/node_modules/pg/lib/connection.js:380:19)
backend_1             |     at Socket.<anonymous> (/home/node/app/node_modules/pg/lib/connection.js:116:22)
backend_1             |     at Socket.emit (events.js:198:13)
backend_1             |     at addChunk (_stream_readable.js:288:12)
backend_1             |     at readableAddChunk (_stream_readable.js:269:11)
backend_1             |     at Socket.Readable.push (_stream_readable.js:224:10)
backend_1             |     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```
